# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy server source code
COPY src/epics-mcp-server ./src/epics-mcp-server

# Set environment variables for Python
ENV PYTHONUNBUFFERED=1

# Default command to run the MCP server over stdio
CMD ["python", "-u", "src/epics-mcp-server/server_by_stdio.py"]
